%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/melodic/.*$
%global __requires_exclude_from ^/opt/ros/melodic/.*$

Name:           ros-melodic-wave-gazebo-plugins
Version:        1.3.0
Release:        1%{?dist}
Summary:        ROS wave_gazebo_plugins package

License:        TBD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-gazebo-ros
BuildRequires:  eigen3-devel
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-gazebo-ros

%description
This package contains Gazebo plugins for the simulation of water surface waves
and hydrostatic and hydrodynamics forces.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/melodic

%changelog
* Thu Dec 26 2019 Rhys Mainwaring <rhys.mainwaring@me.com> - 1.3.0-1
- Autogenerated by Bloom

* Fri Oct 04 2019 Rhys Mainwaring <rhys.mainwaring@me.com> - 1.2.6-1
- Autogenerated by Bloom

* Thu Sep 19 2019 Rhys Mainwaring <rhys.mainwaring@me.com> - 1.2.5-1
- Autogenerated by Bloom

* Fri Sep 06 2019 Rhys Mainwaring <rhys.mainwaring@me.com> - 1.2.2-1
- Autogenerated by Bloom

* Thu Sep 05 2019 Rhys Mainwaring <rhys.mainwaring@me.com> - 1.2.1-1
- Autogenerated by Bloom

* Mon Aug 19 2019 Rhys Mainwaring <rhys.mainwaring@me.com> - 1.2.0-1
- Autogenerated by Bloom

* Wed Jul 03 2019 Rhys Mainwaring <rhys.mainwaring@me.com> - 1.1.1-1
- Autogenerated by Bloom

* Mon Jul 01 2019 Rhys Mainwaring <rhys.mainwaring@me.com> - 1.1.0-1
- Autogenerated by Bloom

