Name:           ros-melodic-vrx-gazebo
Version:        1.2.0
Release:        1%{?dist}
Summary:        ROS vrx_gazebo package

Group:          Development/Libraries
License:        Apache 2.0
URL:            http://wiki.ros.org/vrx_gazebo
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-gazebo-dev
Requires:       ros-melodic-gazebo-ros >= 2.5.17
Requires:       ros-melodic-geographic-msgs
Requires:       ros-melodic-joy
Requires:       ros-melodic-joy-teleop
Requires:       ros-melodic-message-runtime
Requires:       ros-melodic-std-msgs
Requires:       ros-melodic-wamv-gazebo
Requires:       ros-melodic-wave-gazebo
Requires:       ros-melodic-xacro
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-gazebo-dev
BuildRequires:  ros-melodic-gazebo-ros >= 2.5.17
BuildRequires:  ros-melodic-geographic-msgs
BuildRequires:  ros-melodic-joy
BuildRequires:  ros-melodic-joy-teleop
BuildRequires:  ros-melodic-message-runtime
BuildRequires:  ros-melodic-std-msgs
BuildRequires:  ros-melodic-wamv-gazebo
BuildRequires:  ros-melodic-wave-gazebo
BuildRequires:  ros-melodic-xacro
Obsoletes:      ros-melodic-vmrc-gazebo

%description
The ROS package for the RobotX competition running in Gazebo.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Mon Aug 19 2019 Carlos Aguero <caguero@osrfoundation.org> - 1.2.0-1
- Autogenerated by Bloom

* Wed Jul 03 2019 Carlos Aguero <caguero@osrfoundation.org> - 1.1.1-1
- Autogenerated by Bloom

* Mon Jul 01 2019 Carlos Aguero <caguero@osrfoundation.org> - 1.1.0-1
- Autogenerated by Bloom

* Fri Mar 01 2019 Carlos Aguero <caguero@osrfoundation.org> - 1.0.1-0
- Autogenerated by Bloom

* Thu Feb 28 2019 Carlos Aguero <caguero@osrfoundation.org> - 1.0.0-1
- Autogenerated by Bloom

* Thu Feb 28 2019 Carlos Aguero <caguero@osrfoundation.org> - 1.0.0-0
- Autogenerated by Bloom

