%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/melodic/.*$
%global __requires_exclude_from ^/opt/ros/melodic/.*$

Name:           ros-melodic-wamv-gazebo
Version:        1.3.0
Release:        1%{?dist}
Summary:        ROS wamv_gazebo package

License:        Apache 2.0
URL:            http://wiki.ros.org/wamv_gazebo
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-gazebo-plugins
Requires:       ros-melodic-hector-gazebo-plugins
Requires:       ros-melodic-robot-localization
Requires:       ros-melodic-usv-gazebo-plugins
Requires:       ros-melodic-velodyne-gazebo-plugins
Requires:       ros-melodic-wamv-description
Requires:       ros-melodic-xacro
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-gazebo-plugins
BuildRequires:  ros-melodic-hector-gazebo-plugins
BuildRequires:  ros-melodic-robot-localization
BuildRequires:  ros-melodic-usv-gazebo-plugins
BuildRequires:  ros-melodic-velodyne-gazebo-plugins
BuildRequires:  ros-melodic-wamv-description
BuildRequires:  ros-melodic-xacro

%description
Provides templates and examples for integrating the WAM-V model into gazebo with
dynamics, sensors, etc.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/melodic

%changelog
* Thu Dec 26 2019 Carlos Aguero <caguero@osrfoundation.org> - 1.3.0-1
- Autogenerated by Bloom

* Fri Oct 04 2019 Carlos Aguero <caguero@osrfoundation.org> - 1.2.6-1
- Autogenerated by Bloom

* Thu Sep 19 2019 Carlos Aguero <caguero@osrfoundation.org> - 1.2.5-1
- Autogenerated by Bloom

* Fri Sep 06 2019 Carlos Aguero <caguero@osrfoundation.org> - 1.2.2-1
- Autogenerated by Bloom

* Thu Sep 05 2019 Carlos Aguero <caguero@osrfoundation.org> - 1.2.1-1
- Autogenerated by Bloom

* Mon Aug 19 2019 Carlos Aguero <caguero@osrfoundation.org> - 1.2.0-1
- Autogenerated by Bloom

* Wed Jul 03 2019 Carlos Aguero <caguero@osrfoundation.org> - 1.1.1-1
- Autogenerated by Bloom

* Mon Jul 01 2019 Carlos Aguero <caguero@osrfoundation.org> - 1.1.0-1
- Autogenerated by Bloom

* Fri Mar 01 2019 Carlos Aguero <caguero@osrfoundation.org> - 1.0.1-0
- Autogenerated by Bloom

* Thu Feb 28 2019 Carlos Aguero <caguero@osrfoundation.org> - 1.0.0-1
- Autogenerated by Bloom

* Thu Feb 28 2019 Carlos Aguero <caguero@osrfoundation.org> - 1.0.0-0
- Autogenerated by Bloom

